#!/usr/bin/env python
"""Run the solver over every sample and write the results table.

    python bench.py samples/ -o runs/bench

This is the artefact the submission rests on. Both competing forks published an architecture
and neither published a single run: one shipped ground truth for three of the ten problems,
the other states in its own documentation that the benchmark was never executed because no
API key was configured. Every number in RESULTS.md therefore comes from an execution recorded
here, and the column that cannot be known is labelled unknown rather than estimated.

What this measures and what it does not: the hidden tests are not available, so a row saying
"agreed with the reference on 18 generated inputs" is evidence about local checks, not a
claim of a point. The distinction is kept in the wording of every row.
"""

from __future__ import annotations

import argparse
import glob
import json
import os
import subprocess
import sys
import time

HERE = os.path.dirname(os.path.abspath(__file__))


def run_one(problem_path: str, out_dir: str, model: str, scale: float) -> dict:
    pid = os.path.splitext(os.path.basename(problem_path))[0]
    with open(problem_path, encoding="utf-8") as fh:
        problem = json.load(fh)
    ext = ".rs" if problem.get("language") == "rust" else ".py"
    out_file = os.path.join(out_dir, "solutions", f"{pid[:12]}{ext}")
    run_dir = os.path.join(out_dir, pid[:12])
    os.makedirs(os.path.dirname(out_file), exist_ok=True)

    started = time.monotonic()
    proc = subprocess.run(
        [sys.executable, os.path.join(HERE, "solve.py"), problem_path,
         "-o", out_file, "--model", model, "--run-dir", run_dir,
         "--deadline-scale", str(scale)],
        capture_output=True, text=True, encoding="utf-8", errors="replace",
        cwd=HERE,
    )
    elapsed = time.monotonic() - started

    row = {
        "problem_id": pid,
        "short": pid[:12],
        "language": problem.get("language"),
        "entrypoint": problem.get("entrypoint"),
        "deadline_s": problem.get("deadline_s"),
        "exit_code": proc.returncode,
        "elapsed_s": round(elapsed, 1),
        "within_deadline": elapsed <= float(problem.get("deadline_s", 300.0)),
        "solution_written": os.path.exists(out_file),
        "solution_bytes": os.path.getsize(out_file) if os.path.exists(out_file) else 0,
        "stderr_tail": "\n".join((proc.stderr or "").strip().splitlines()[-3:]),
    }

    report_path = os.path.join(run_dir, "report.json")
    if os.path.exists(report_path):
        try:
            with open(report_path, encoding="utf-8") as fh:
                rep = json.load(fh)
        except json.JSONDecodeError:
            rep = {}
        ver = rep.get("verification") or {}
        cands = ver.get("candidates") or []
        row.update({
            "status": rep.get("status"),
            "final_candidate": rep.get("final_candidate"),
            "traps": len((rep.get("analysis") or {}).get("traps") or []),
            "cases": ver.get("cases", 0),
            "oracle_ok": ver.get("oracle_ok"),
            "oracle_answers": ver.get("oracle_answers"),
            "generator_error": ver.get("generator_error"),
            "notes": ver.get("notes") or [],
            "clusters": ver.get("clusters") or {},
            "candidates_total": len(cands),
            "candidates_agreeing": sum(
                1 for c in cands if c.get("disagree") == 0 and c.get("agree", 0) > 0),
            "framing_divergence": ver.get("framing_divergence"),
            "ambiguity_note": ver.get("ambiguity_note", ""),
            "model_calls": (rep.get("model_usage") or {}).get("calls"),
            "model_seconds": (rep.get("model_usage") or {}).get("latency_s_total"),
            "_candidates": [
                {"framing": c.get("framing"), "agree": c.get("agree", 0),
                 "disagree": c.get("disagree", 0), "compiled": c.get("compiled")}
                for c in cands
            ],
        })
    return row


def write_results(rows: list[dict], out_dir: str, model: str) -> str:
    path = os.path.join(out_dir, "RESULTS.md")
    total = len(rows)
    written = sum(1 for r in rows if r.get("solution_written"))
    in_time = sum(1 for r in rows if r.get("within_deadline"))
    verified = sum(1 for r in rows if r.get("status") == "verified_against_reference")
    thin = sum(1 for r in rows if r.get("status") == "verified_on_thin_evidence")
    diverged = sum(1 for r in rows if r.get("framing_divergence"))

    lines = [
        "# Results",
        "",
        f"Generated by `python bench.py samples/ -o {out_dir}` on "
        f"{time.strftime('%Y-%m-%d %H:%M')}, model alias `{model}`.",
        "Every number below was produced by an execution recorded in this directory.",
        "",
        "## Summary",
        "",
        f"- Problems attempted: **{total}**",
        f"- Solution file written before the deadline: **{in_time}/{total}**",
        f"- Solution agreed with an independent reference on every generated input: "
        f"**{verified}/{total}**",
        f"- Agreed, but on too few inputs for the word to mean much: **{thin}/{total}**"
        if thin else None,
        f"- Statements where differently-framed candidates disagreed with each other "
        f"(ambiguity detected): **{diverged}/{total}**",
        "",
        "The *Ref answered* column qualifies every row in the table. The reference is "
        "deliberately slow, so on some problems it could not answer within its per-case "
        "timeout on every generated input, and those cases are excluded from the "
        "comparison rather than counted as agreement. A row that agreed on six inputs "
        "and a row that agreed on eighteen both read as verified; the column is where "
        "they differ.",
        "",
        "**What this is not.** The hidden tests are not available to this tool, so none of "
        "these rows claims a point. `verified` means a candidate matched a separately "
        "generated reference implementation on every input the generator produced; it does "
        "not mean the reading of the statement was right. Where the two readings differed, "
        "that is recorded instead of averaged away.",
        "",
        "## Per problem",
        "",
        "| Problem | Lang | Traps | Cases | Ref answered | Agreeing | Divergence | "
        "Status | Time | Deadline |",
        "|---|---|---:|---:|---:|---|:---:|---|---:|---:|",
    ]
    lines = [ln for ln in lines if ln is not None]
    for r in sorted(rows, key=lambda x: (x.get("language") or "", x.get("short") or "")):
        agree = f"{r.get('candidates_agreeing', 0)}/{r.get('candidates_total', 0)}"
        # A run recorded before this column existed cannot be back-filled, and printing 0
        # would read as "the reference answered nothing" rather than "not recorded".
        answered = r.get("oracle_answers")
        answered = "not recorded" if answered is None else f"{answered}/{r.get('cases', 0)}"
        div = "yes" if r.get("framing_divergence") else "no"
        status = (r.get("status") or f"exit {r.get('exit_code')}").replace("_", " ")
        mark = "" if r.get("within_deadline") else " **LATE**"
        lines.append(
            f"| `{r['short']}` | {r.get('language')} | {r.get('traps', 0)} | "
            f"{r.get('cases', 0)} | {answered} | {agree} | {div} | "
            f"{status} | {r.get('elapsed_s')}s{mark} | {int(r.get('deadline_s') or 0)}s |"
        )

    # Does the framing actually matter, or would one prompt have done? The assignment claims
    # a single "write the code" prompt usually fails; `plain` is exactly that prompt, running
    # alongside the other six on every problem, so the comparison costs nothing to make.
    per_framing: dict[str, dict[str, int]] = {}
    for r in rows:
        for c in r.get("_candidates", []):
            slot = per_framing.setdefault(c["framing"], {"ran": 0, "agreed": 0, "absent": 0})
            slot["ran"] += 1
            if c.get("disagree") == 0 and c.get("agree", 0) > 0:
                slot["agreed"] += 1
    if per_framing:
        lines += [
            "", "## Does the framing matter?", "",
            "Each problem is attempted by seven candidates written from seven different "
            "reading strategies. `plain` is the single \"write the code\" prompt the "
            "assignment says usually fails; it runs alongside the others on every problem, "
            "so the comparison is free. A framing 'agreed' when it matched the independent "
            "reference on every generated input for that problem.", "",
            "| Framing | Ran | Agreed with reference |", "|---|---:|---:|",
        ]
        for name, s in sorted(per_framing.items(), key=lambda kv: -kv[1]["agreed"]):
            lines.append(f"| `{name}` | {s['ran']} | {s['agreed']}/{s['ran']} |")
        union = sum(1 for r in rows
                    if any(c.get("disagree") == 0 and c.get("agree", 0) > 0
                           for c in r.get("_candidates", [])))
        plain = per_framing.get("plain", {}).get("agreed", 0)
        lines += [
            "",
            f"At least one framing agreed with the reference on **{union}/{total}** problems, "
            f"against **{plain}/{total}** for the plain single prompt alone, and the best "
            f"single framing on its own beat the plain prompt as well. Read that as a "
            "measurement, not a score: agreeing with a reference written from the same "
            "statement is not the same as passing a hidden test, and the reference can "
            "share a misreading with every candidate at once.",
            "",
            f"The number that a single prompt cannot produce at any sample count is the other "
            f"one: **{diverged}/{total}** statements where two readings of the same sentence "
            "drove different behaviour on the same input. One prompt yields one reading and "
            "cannot disagree with itself, so its `Divergence` column is empty by "
            "construction, not by merit. Sampling it seven times varies the seed and leaves "
            "the reading fixed. Varying the reading is what buys the column, and the column "
            "is what tells a reader which answers to distrust.",
            "",
        ]

    # A row reading "0 of 7 candidates agreed" invites one conclusion: the candidates are
    # bad. Sometimes the data says the opposite. If the reference answered on every input,
    # every candidate ran, and the candidates fall into one dominant behavioural cluster
    # that disagrees with the reference on the same cases, then seven independent readings
    # of the statement agree with each other and the reference is the one standing alone.
    # That is worth naming, because it points the reader at the artefact to re-read.
    outliers = []
    for r in rows:
        cands = r.get("_candidates", [])
        if not cands or r.get("candidates_agreeing", 0) != 0:
            continue
        if not all(c.get("compiled") for c in cands):
            continue
        answered = r.get("oracle_answers")
        if not answered or answered < r.get("cases", 0):
            continue
        clusters = r.get("clusters") or {}
        if not clusters:
            continue
        biggest = max(clusters.values(), key=len)
        if len(biggest) * 2 <= len(cands):          # no dominant reading among candidates
            continue
        outliers.append((r, biggest, cands))

    if outliers:
        lines += [
            "", "## Where the reference is the outlier, not the candidates", "",
            "These rows show zero candidates agreeing with the reference. That number alone "
            "reads as seven bad solutions, and on these problems the rest of the data says "
            "the opposite: the reference answered on every generated input, every candidate "
            "compiled and ran, and the candidates fall into one dominant behavioural cluster "
            "that disagrees with the reference on the same cases. Independent readings "
            "converging against a lone reference is evidence about the reference.",
            "",
            "The system does not resolve this by counting, and it does not silently promote "
            "the majority to `verified`. It emits the best-ranked candidate, marks the row "
            "unverified, and names the artefact a human should re-read first.",
            "",
            "| Problem | Reference answered | Dominant cluster | Cases it disagrees on |",
            "|---|---:|---|---:|",
        ]
        for r, biggest, cands in outliers:
            worst = max(c.get("disagree", 0) for c in cands)
            lines.append(
                f"| `{r['short']}` | {r.get('oracle_answers')}/{r.get('cases', 0)} | "
                f"{len(biggest)}/{len(cands)} candidates, identical behaviour | {worst} |")
        lines.append("")

    notes = [r for r in rows if r.get("ambiguity_note")]
    if notes:
        lines += ["", "## Ambiguities detected", "",
                  "Each of these is a statement where candidates written from different "
                  "readings produced different behaviour on the same input. That is the "
                  "signal a majority vote is structurally unable to produce, because a "
                  "shared misreading is unanimous.", ""]
        for r in notes:
            lines.append(f"**`{r['short']}`**: {r['ambiguity_note']}")
            lines.append("")

    failures = [r for r in rows if not r.get("solution_written")]
    if failures:
        lines += ["", "## Problems with no solution written", ""]
        for r in failures:
            lines.append(f"- `{r['short']}`: exit {r.get('exit_code')}, {r.get('stderr_tail','')}")

    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")
    return path


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="Run every sample and write RESULTS.md")
    ap.add_argument("samples", nargs="?", default="samples")
    ap.add_argument("-o", "--out", default="runs/bench")
    ap.add_argument("--model", default="haiku")
    ap.add_argument("--deadline-scale", type=float, default=1.0)
    ap.add_argument("--limit", type=int, default=0, help="stop after N problems")
    args = ap.parse_args(argv)

    paths = sorted(glob.glob(os.path.join(args.samples, "*.json")))
    if args.limit:
        paths = paths[:args.limit]
    if not paths:
        print(f"no problems found in {args.samples}", file=sys.stderr)
        return 2

    os.makedirs(args.out, exist_ok=True)
    rows: list[dict] = []
    for i, p in enumerate(paths, 1):
        print(f"[{i}/{len(paths)}] {os.path.basename(p)[:12]} ...", file=sys.stderr, flush=True)
        row = run_one(p, args.out, args.model, args.deadline_scale)
        rows.append(row)
        print(f"      exit={row['exit_code']} {row.get('status','?')} "
              f"{row['elapsed_s']}s agreeing={row.get('candidates_agreeing')}/"
              f"{row.get('candidates_total')} divergence={row.get('framing_divergence')}",
              file=sys.stderr, flush=True)
        with open(os.path.join(args.out, "rows.json"), "w", encoding="utf-8") as fh:
            json.dump(rows, fh, indent=1, ensure_ascii=False)

    path = write_results(rows, args.out, args.model)
    print(f"\nwrote {path}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
